project/project/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;


using System.Web.Mvc;


namespace project.Controllers
{
    public class ChartController : Controller
    {
        prEntities db = new prEntities();
        // GET: Chart
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult VisualProductResult() 
        {

            return Json(Prolist());
        }
        public List<MusteriChart> Prolist()
        {
            List<MusteriChart> cs = new List<MusteriChart>();
            cs = db.Siparis.GroupBy(s => s.Musteri.Adi)
                .Select(b=> new MusteriChart
                {
                    MusteriAdi = b.Key,
                    SiparisTutari = b.Sum(s=> s.SiparisTutar),
                }).ToList();
            return cs;
        }
    }

   
}

project/project/Controllers/MusterisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using project;

namespace project.Controllers
{
    public class MusterisController : Controller
    {
        private prEntities db = new prEntities();

        // GET: Musteris
        public ActionResult Index()
        {
            var musteri = db.Musteri.Include(m => m.Bayi);
            return View(musteri.ToList());
        }

        // GET: Musteris/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Musteri musteri = db.Musteri.Find(id);
            if (musteri == null)
            {
                return HttpNotFound();
            }
            return View(musteri);
        }

        // GET: Musteris/Create
        public ActionResult Create()
        {
            ViewBag.BayiID = new SelectList(db.Bayi, "id", "BayiAdi");
            return View();
        }

        // POST: Musteris/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,BayiID,Adi,Soyadi,VergiNo")] Musteri musteri)
        {
            if (ModelState.IsValid)
            {
                db.Musteri.Add(musteri);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BayiID = new SelectList(db.Bayi, "id", "BayiAdi", musteri.BayiID);
            return View(musteri);
        }

        // GET: Musteris/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Musteri musteri = db.Musteri.Find(id);
            if (musteri == null)
            {
                return HttpNotFound();
            }
            ViewBag.BayiID = new SelectList(db.Bayi, "id", "BayiAdi", musteri.BayiID);
            return View(musteri);
        }

        // POST: Musteris/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,BayiID,Adi,Soyadi,VergiNo")] Musteri musteri)
        {
            if (ModelState.IsValid)
            {
                db.Entry(musteri).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BayiID = new SelectList(db.Bayi, "id", "BayiAdi", musteri.BayiID);
            return View(musteri);
        }

        // GET: Musteris/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Musteri musteri = db.Musteri.Find(id);
            if (musteri == null)
            {
                return HttpNotFound();
            }
            return View(musteri);
        }

        // POST: Musteris/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Musteri musteri = db.Musteri.Find(id);
            db.Musteri.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

project/project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.semanticui.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.semanticui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.js"></script>


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

  
</head>
<body>
    <br />
    <br />
    <br />
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PROJECT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Anasayfa", "Index", "Chart")</li>
                    <li>@Html.ActionLink("Genel Tablo", "Index", "MusteriVm")</li>
                    <li>@Html.ActionLink("Bayi", "Index", "Bayi")</li>
                    <li>@Html.ActionLink("Müşteriler", "Index", "Musteris")</li>
                    <li>@Html.ActionLink("Siparis", "Index", "Siparis")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">

        @RenderBody()
        <hr />


        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script>
        $(document).ready(function () {
            $('#example').DataTable();
        });
    </script>


</body>
</html>